title: Zhizhou's Blog
name: "Zhizhou Yu's Blog"
author: Zhizhou Yu
description: Personal Essays.
profile_url: "https://zhizhou-yu.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
